name: CI

on:
  push:
    branches:
      - macbuild

defaults:
  run:
    shell: bash

jobs:
        
  macOS:
    name: Mac
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        name: [ Release ]
        include:
          - name: Release
            type: Release
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
    - name: Install Homebrew dependencies
      run: |
        sudo rm /usr/local/bin/2to3-3.* || true
        sudo rm /usr/local/bin/idle3.* || true
        sudo rm /usr/local/bin/pydoc3.* || true
        sudo rm /usr/local/bin/python3.* || true
        sudo rm /usr/local/bin/2to3 || true
        sudo rm /usr/local/bin/idle3 || true
        sudo rm /usr/local/bin/pydoc3 || true
        sudo rm /usr/local/bin/python3 || true
        sudo rm /usr/local/bin/python3-config || true
        brew update || true
        brew unlink python || true
        brew link --overwrite --force python || true
        brew unlink python@3.12 || true
        brew link --overwrite --force python@3.12 || true
        brew install --overwrite lftp automake pcre qt@5
        brew link --overwrite --force qt@5
    - name: Build
      run: |
        mkdir build
        pushd build
        cmake -DENABLE_METAL=On -DCMAKE_BUILD_TYPE=${{ matrix.type }} ..
        make -j8
        popd
    - if: matrix.type == 'Release'
      name: Preparing for deploy
      run: ./util/buildscripts/scripts/prepare_deps_macos.sh ./build/bin/qrenderdoc.app/Contents/MacOS/qrenderdoc
    - if: matrix.type == 'Release'
      name: Packaging artifacts for nightly build
      id: package
      run: |
        FNAME="RenderDoc_macOS_"`git rev-parse HEAD`.zip
        zip -r "${FNAME}" build/bin
        ls -lh "${FNAME}"
        echo "artifact=$FNAME" >> $GITHUB_OUTPUT
    - if: matrix.type == 'Release'
      name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.package.outputs.artifact }}
        path: ${{ steps.package.outputs.artifact }}
